### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by AntuzAdolfo** [FrancoDelfino/Proyecto-DigitalHouse-MercLiebre-FrancoDelfino#1]
- [x] 1 - Cumple el primer punto (Respecto a la estructura del sitio visualizar que contenga estos elementos cada sección) porque contiene todos los elementos: 
Header:
● Logo
● Barra de búsqueda
● Comprá en cuotas y sin tarjeta de crédito
● Barra de navegación:
● Ofertas
● Tiendas Oficiales
● Vender
● Ayuda
● Login
● Registro
● Mis compras

Main:
● Sección basada en las últimas visitas
● Sección de ofertas

Footer:
● Pagá con tarjeta o en efectivo
● Envío gratis desde $ 2.500
● Seguridad, de principio a fin
● Copyright © 1999-2022 MercadoLiebre S.R.L.

- [x] 2 - Cumple el segundo punto (Haciendo foco en los estilos del pie de página (Footer)) porque: 
*El contenido de todos los artículos esta centrado.
*Los íconos tienen un tamaño de 2em y un margen inferior de separación de 10 pixeles.

- [x] 3 - Cumple el tercer punto porque el sitio si se adapta a distintas resoluciones de pantalla. 

- [x] 4 - Cumple el cuarto punto porque el sitio si cuenta con un formulario de registro de usuarios.

- [x] 5 - Cumple el quinto punto porque el sitio si cuenta con un formulario de login.

- [x] 6 - No cumple el sexto punto porque no se muestra mensajes de error cuando un usuario coloca información equivocada en un campo de los formularios. Se puede corregir agregando verificaciones colocando:  
```
<span>Contraseña no es igual a la verificada</span> Agregarle color de letra rojo

<span>El formato del mail es incorrecto, debería contener con un "@", ".com"</span>
``` 

- [x] 7 - No cumple el séptimo punto porque el search bar no es un formulario. Se puede corregir envolviendo el input en las etiquetas
```
<form><input class="searchbar" type="text" placeholder="Buscar productos, marcas"></form>
```

- [x] 8 - Cumple  el octavo punto porque si se utilizan animaciones y propiedades de transición de CSS.

- [x] 9 - Está muy bien hecho en general, colores adecuados, textos legibles y artículos bien ubicados

- [x] 10 - Podría mejorar que cuando el usuario escriba en la barra de direcciones y lleve a una ruta que no existe, que muestre un mensaje acorde y tenga un link redireccione a Home. Se puede corregir escribiendo lo siguiente:
```
/*Colocarlo al final para que no genere conflictos con las demás rutas*/
app.get('*', (req, res) => {
    res.send(`
    <div>
       <h1>Esta página no existe</h1>
       <a href="/home">Volver al Home</a>    
    </div>
    `)
})
```

**Comment by FrancoDelfino** [comment]
Hola Adolfo, estoy corrigiendo los errores que me dijiste, pero no me queda claro el de validar los formularios con <span>, me pondrias un ejemplo de codigo para ver como quedaria en una linea? Gracias

**Comment by AntuzAdolfo** [comment]
Hola Franco, lo de validación creo que lo veremos más adelante, perdón, confundí el punto 6, pero el tema es que no me debería dejar Enviar la información de Login y Register, faltaría agregarle required

```
<input required>
```

A cada uno de los inputs, salvo el de checkbox

**Comment by FrancoDelfino** [comment]
Ya estan resueltos todos los puntos que estaban mal! Muchas gracias!
