### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by onurera** [FrancoDelfino/Proyecto-DigitalHouse-MercLiebre-FrancoDelfino#2]
1. Cumple el primer punto (Respecto a la estructura del sitio visualizar que contenga estos elementos cada sección) porque contiene todos los elementos:

Header:
    - Logo
    - Barra de búsqueda
    - Comprá en cuotas y sin tarjeta de crédito

Barra de navegación:
      - Ofertas
      - Tiendas Oficiales
      - Vender
      - Ayuda
      - Login
      - Registro
      - Mis compras

Main:
      - Sección basada en las últimas visitas
      - Sección de ofertas

Footer:
      - Pagá con tarjeta o en efectivo
      - Envío gratis desde $ 2.500
      - Seguridad, de principio a fin
      - Copyright © 1999-2022 MercadoLiebre S.R.L.

2. Cumple el segundo punto (Haciendo foco en los estilos del pie de página (Footer)) porque:
  - El contenido de todos los artículos está centrado.
  - Los íconos tienen un tamaño de 2em y un margen inferior de separación de 10 píxeles.

3. Cumple el tercer punto porque el sitio se adapta a distintas resoluciones de pantalla.

4. Cumple el cuarto punto porque el sitio cuenta con un formulario de registro de usuarios.

5. Cumple el quinto punto porque el sitio cuenta con un formulario de login.

6. Cumple el sexto punto. Se muestran mensajes de error cuando un usuario coloca información
equivocada en un campo de los formularios.

7. Cumple el séptimo punto. El search bar es un formulario.

8. Cumple el octavo punto porque se utilizan animaciones y propiedades de transición de CSS.

9. Está muy bien hecho, con colores adecuados y tamaño de textos legibles.

10. Podría mejorar los márgenes de la clase titulares entre el header y los artículos, ya que están muy juntos.

**Comment by FrancoDelfino** [comment]
Muchas gracias!
